[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
priority=1

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
startsecs=2

[program:laravel-worker]
command=php /var/www/html/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
priority=5
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log